# Generated by Django 3.0.5 on 2020-04-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('tweets', models.PositiveIntegerField()),
                ('following', models.PositiveIntegerField()),
                ('followers', models.PositiveIntegerField()),
                ('potential_fake', models.BooleanField(default=False)),
                ('is_fake', models.BooleanField(default=False)),
                ('reported', models.BooleanField(default=False)),
                ('banned', models.BooleanField(default=False)),
                ('tag', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
    ]
