# Generated by Django 3.0.5 on 2020-05-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
